name: Publish Docker images
on:
  push:
    branches:
      - master
jobs:
  cuda_image_build:
    name: CUDA image build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: free disk space
      run: | 
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Build the CUDA Docker image
      run: docker build . --file Dockerfile-CUDA --tag wav2letter/wav2letter:cuda-latest
    - name: Docker login
      env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u=$USER -p=$PASSWORD
    - name: Push image with the latest tag
      run: docker push wav2letter/wav2letter:cuda-latest
    - name: Tag revision
      run: docker tag wav2letter/wav2letter:cuda-latest wav2letter/wav2letter:cuda-`git rev-parse --short HEAD`
    - name: Push image with the revision tag
      run: docker push wav2letter/wav2letter:cuda-`git rev-parse --short HEAD`
    - name: Docker logout
      run: docker logout
  cpu_image_build:
    name: CPU image build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the CPU Docker image
      run: docker build . --file Dockerfile-CPU --tag wav2letter/wav2letter:cpu-latest
    - name: Docker login
      env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u=$USER -p=$PASSWORD
    - name: Push image with the latest tag
      run: docker push wav2letter/wav2letter:cpu-latest
    - name: Tag revision
      run: docker tag wav2letter/wav2letter:cpu-latest wav2letter/wav2letter:cpu-`git rev-parse --short HEAD`
    - name: Push image with the revision tag
      run: docker push wav2letter/wav2letter:cpu-`git rev-parse --short HEAD`
    - name: Docker logout
      run: docker logout
  inference_image_build:
    name: Inference image build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Inference Docker image
      run: docker build . --file Dockerfile-Inference --tag wav2letter/wav2letter:inference-latest
    - name: Docker login
      env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u=$USER -p=$PASSWORD
    - name: Push image with the latest tag
      run: docker push wav2letter/wav2letter:inference-latest
    - name: Tag revision
      run: docker tag wav2letter/wav2letter:inference-latest wav2letter/wav2letter:inference-`git rev-parse --short HEAD`
    - name: Push image with the revision tag
      run: docker push wav2letter/wav2letter:inference-`git rev-parse --short HEAD`
    - name: Docker logout
      run: docker logout
