# ==================================================================
# module list
# ------------------------------------------------------------------
# flashlight       master     (git, CPU backend)
# ==================================================================

FROM flml/flashlight:cpu-base-consolidation-latest

# just in case for visibility
ENV PATH="/opt/cmake/bin:$PATH"
ENV MKLROOT="/opt/intel/mkl"
ENV KENLM_ROOT=/opt/kenlm

# ==================================================================
# flashlight with CPU backend
# ------------------------------------------------------------------
# Setup and build flashlight
RUN mkdir /root/flashlight

COPY . /root/flashlight

RUN cd /root/flashlight && mkdir -p build && \
    cd build && cmake .. -DCMAKE_BUILD_TYPE=Release \
                         -DCMAKE_INSTALL_PREFIX=/opt/flashlight \
                         -DFL_BACKEND=CPU \
                         -DFL_LIBRARIES_USE_CUDA=OFF \
                         -DDNNL_DIR=/opt/onednn/lib/cmake/dnnl \
                         -DGloo_INCLUDE_DIR=/opt/gloo/include \
                         -DGloo_NATIVE_LIBRARY=/opt/gloo/lib/libgloo.a && \
    make -j$(nproc) && make install && \
    cd ../ && rm -rf build
