# ==================================================================
# module list
# ------------------------------------------------------------------
# Ubuntu           18.04
# OpenMPI          latest       (apt)
# CUDA             11.1
# CuDNN            8-dev
# cmake            3.10         (oficial binaries)
# MKL              2020.4-912   (apt)
# arrayfire        3.7.3        (git, CUDA backend)
# libsndfile       latest       (apt, 1.0.28-4)
# FFTW             latest       (apt)
# KenLM            4a27753      (git)
# GLOG             latest       (apt)
# gflags           latest       (apt)
# python3          latest       (apt)
# boost            1.75.0       (source)
# ==================================================================

FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04 as build

# If the driver is not found (during docker build) the cuda driver api need to be linked against the
# libcuda.so stub located in the lib[64]/stubs directory
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/lib/libcuda.so.1 

ENV DEBIAN_FRONTEND=noninteractive

RUN rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        git \
        g++ \
        # for cmake
        zlib1g-dev libcurl4-openssl-dev \
        # for MKL
        apt-transport-https  gpg-agent gnupg2 \
        # OpenMPI
        libopenmpi-dev libomp-dev openmpi-bin \
        # nccl: for flashlight
        libnccl2 libnccl-dev libglfw3-dev \
        # libsndfile
        libsndfile1-dev \
        # for libsndfile for ubuntu 18.04
        libopus-dev \
        # for Intel's Math Kernel Library (MKL)
        cpio \
        # FFTW
        libfftw3-dev \
        # OpenBlas
        libopenblas-dev \
        # for kenlm
        zlib1g-dev libbz2-dev liblzma-dev \
        # gflags
        libgflags-dev libgflags2.2 \
        # for glog
        libgoogle-glog-dev libgoogle-glog0v5 \
        # for receipts data processing
        sox \
        # for python
        python3-dev python3-pip python3-distutils
# ==================================================================
# python (for bindings)
# ------------------------------------------------------------------
RUN ln -s /usr/bin/python3 /usr/local/bin/python && \
    python3 -m pip --no-cache-dir install --upgrade setuptools numpy sox tqdm
# ==================================================================
# cmake 3.10
# ------------------------------------------------------------------
RUN apt-get purge -y cmake && \
    mkdir /opt/cmake && \
    curl -sSLo - https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.tar.gz | tar -xz -C /opt/cmake --strip-components 1
ENV PATH="/opt/cmake/bin:$PATH"
# ==================================================================
# MKL https://software.intel.com/en-us/mkl
# ------------------------------------------------------------------
RUN curl -sSLo - https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | apt-key add && \
    sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' && \
    apt-get update && \
    apt-get install -y intel-mkl-64bit-2020.4-912
ENV MKLROOT="/opt/intel/mkl"
# ==================================================================
# boost 1.75 (for arrayfire and kenlm)
# ------------------------------------------------------------------
RUN cd /tmp && \
    curl -sSLo - https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 | tar --bzip2 -x && \
    cd boost_1_75_0 && \
    ./bootstrap.sh --prefix=/opt/boost && \
    ./b2 && \
    ./b2 install
# ==================================================================
# arrayfire with CUDA backend https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#cuda-backend-dependencies
# ------------------------------------------------------------------
RUN cd /tmp && \
    git clone --branch v3.7.3 --depth 1 --recursive --shallow-submodules https://github.com/arrayfire/arrayfire.git && \
    mkdir -p arrayfire/build && \
    cd arrayfire/build && \
    CXXFLAGS=-DOS_LNX cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/arrayfire -DAF_BUILD_CUDA=ON -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DAF_WITH_IMAGEIO=OFF .. && \
    make -j$(nproc) && \
    make install -j$(nproc)
# ==================================================================
# KenLM https://github.com/kpu/kenlm
# ------------------------------------------------------------------
RUN cd /tmp && \
    git clone --depth 1 https://github.com/kpu/kenlm.git && \
    mkdir -p kenlm/build && \
    cd kenlm/build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/kenlm -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && \
    make -j$(nproc) && \
    make install -j$(nproc)



#############################################################################
#                            SECOND STAGE                                   #
#############################################################################

FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive

# If the driver is not found (during docker build) the cuda driver api need to be linked against the
# libcuda.so stub located in the lib[64]/stubs directory
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/lib/libcuda.so.1 

# install dependencies
RUN rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        git \
        g++ \
        # for cmake
        zlib1g-dev libcurl4-openssl-dev \
        # OpenMPI
        libopenmpi-dev libomp-dev openmpi-bin \
        # nccl: for flashlight
        libnccl2 libnccl-dev libglfw3-dev \
        # libsndfile
        libsndfile1-dev \
        # for libsndfile for ubuntu 18.04
        libopus-dev \
        # for Intel's Math Kernel Library (MKL)
        cpio \
        # FFTW
        libfftw3-dev \
        # OpenBlas
        libopenblas-dev \
        # for kenlm
        zlib1g-dev libbz2-dev liblzma-dev \
        # gflags
        libgflags-dev libgflags2.2 \
        # for glog
        libgoogle-glog-dev libgoogle-glog0v5 \
        # for receipts data processing
        sox \
        # for python
        python3-dev python3-pip python3-distutils && \
    ldconfig && \
    apt-get clean && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /opt/arrayfire /opt/arrayfire
COPY --from=build /opt/kenlm     /opt/kenlm
COPY --from=build /opt/intel     /opt/intel
COPY --from=build /opt/boost     /opt/boost
COPY --from=build /opt/cmake     /opt/cmake

ENV PATH="/opt/cmake/bin:$PATH"
ENV KENLM_ROOT_DIR=/opt/kenlm
ENV MKLROOT="/opt/intel/mkl"
ENV LD_LIBRARY_PATH="/opt/boost/lib:$LD_LIBRARY_PATH"
