# ==================================================================
# module list
# ------------------------------------------------------------------
# flashlight       master     (git, CUDA backend)
# ==================================================================

FROM flml/flashlight:cuda-base-consolidation-latest

# just in case for visibility
ENV MKLROOT="/opt/intel/mkl"

# ==================================================================
# flashlight with CUDA backend
# ------------------------------------------------------------------
# Setup and build flashlight
RUN mkdir /root/flashlight

COPY . /root/flashlight

RUN cd /root/flashlight && mkdir -p build && \
    cd build && cmake .. -DCMAKE_BUILD_TYPE=Release \
                         -DCMAKE_INSTALL_PREFIX=/opt/flashlight \
                         -DFL_BACKEND=CUDA \
                         -DFL_BUILD_ALL_APPS=ON && \
    make install -j$(nproc)
