# ==================================================================
# module list
# ------------------------------------------------------------------
# flashlight       master   (git, CUDA backend)
# ==================================================================

FROM flml/flashlight:cuda-base-consolidation-latest as build

# ==================================================================
# flashlight with GPU backend
# ------------------------------------------------------------------
# Setup and build flashlight
RUN mkdir /tmp/flashlight

COPY . /tmp/flashlight

RUN mkdir -p /tmp/flashlight/build && \
    cd /tmp/flashlight/build && \ 
    cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/opt/flashlight" -DFL_BACKEND="CUDA" -DFL_BUILD_TESTS="ON" .. && \
    make -j$(nproc) && \
    make install -j$(nproc)



#############################################################################
#                            SECOND STAGE                                   #
#############################################################################

FROM nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive

# install dependencies
RUN rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        git \
        g++ \
        # for cmake
        zlib1g-dev libcurl4-openssl-dev \
        # OpenMPI
        libopenmpi-dev libomp-dev openmpi-bin \
        # nccl: for flashlight
        #libnccl2 libnccl-dev libglfw3-dev \
        # libsndfile
        libsndfile1-dev \
        # for libsndfile for ubuntu 18.04
        libopus-dev \
        # for Intel's Math Kernel Library (MKL)
        cpio \
        # FFTW
        libfftw3-dev \
        # OpenBlas
        libopenblas-dev \
        # for kenlm
        zlib1g-dev libbz2-dev liblzma-dev \
        # gflags
        libgflags-dev libgflags2.2 \
        # for glog
        libgoogle-glog-dev libgoogle-glog0v5 \
        # for receipts data processing
        sox \
        # for python
        python3-dev python3-pip python3-distutils && \
    ldconfig && \
    apt-get clean && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /opt/arrayfire  /opt/arrayfire
COPY --from=build /opt/kenlm      /opt/kenlm
COPY --from=build /opt/intel      /opt/intel
COPY --from=build /opt/boost      /opt/boost
COPY --from=build /opt/flashlight /opt/flashlight

ENV KENLM_ROOT_DIR=/opt/kenlm
ENV MKLROOT="/opt/intel/mkl"
ENV LD_LIBRARY_PATH="/opt/boost/lib:$LD_LIBRARY_PATH"
