# ==================================================================
# module list
# ------------------------------------------------------------------
# flashlight       master     (git, CPU backend)
# ==================================================================

FROM flml/flashlight:cpu-base-consolidation-latest

# just in case for visibility
ENV MKLROOT="/opt/intel/mkl"

# ==================================================================
# flashlight with CPU backend
# ------------------------------------------------------------------
# Setup and build flashlight
RUN mkdir /root/flashlight

COPY . /root/flashlight

RUN cd /root/flashlight && mkdir -p build && \
    cd build && cmake .. -DCMAKE_BUILD_TYPE=Release \
                         -DCMAKE_INSTALL_PREFIX=/opt/flashlight \
                         -DFL_BUILD_ALL_APPS=ON \
                         -DFL_BACKEND=CPU \
                         -DGloo_DIR=/opt/gloo/share/cmake \
                         -DDNNL_DIR=/opt/onednn/lib/cmake/dnnl && \
    make install -j$(nproc)
